# Generated by Django 3.1.6 on 2021-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
